using System;
using UnityEngine;
using UnityEngine.UIElements;

public class GameplayPanel : MonoBehaviour
{
    [Header("イベント")]
    public ObjectEventSo playerTurnEnd;

    [Header("UI")]
    private VisualElement rootElement;
    private Label energyAmountLabel, drawAmountLabel, discardAmountLabel, turnLabelLabel;
    private Button endTurnButton;


    private void OnEnable()
    {
        rootElement = GetComponent<UIDocument>().rootVisualElement;

        energyAmountLabel = rootElement.Q<Label>("EnergyAmount");
        drawAmountLabel = rootElement.Q<Label>("DrawAmount");
        discardAmountLabel = rootElement.Q<Label>("DiscardAmount");
        turnLabelLabel = rootElement.Q<Label>("TurnLabel");
        endTurnButton = rootElement.Q<Button>("EndTurn");
        endTurnButton.clicked += OnTurnEnd;

  
        energyAmountLabel.text = "0";
        drawAmountLabel.text = "0";
        discardAmountLabel.text = "0";
        turnLabelLabel.text = "ゲ`ム_始";

    }

    private void OnTurnEnd()
    {
        playerTurnEnd.RaisedEvent(null, this);
    }

    #region UI更新
    public void UpdateDrawDeckAmount(int amount)
    {
        drawAmountLabel.text = amount.ToString();    //ドロ`山札のUIを更新する
    }
    public void UpdateDiscardDeckAmount(int amount)
    {
        discardAmountLabel.text = amount.ToString(); //韦圃のUIを更新する
    }

    public void UpdateEnergyAmount(int amount)
    {
        energyAmountLabel.text = amount.ToString();  //エネルギ`のUIを更新する
    }
    #endregion
    public void OnEnemyTurnBegin()
    {
        endTurnButton.SetEnabled(false);    //长违咯`ン中はボタンがo郡摔胜
        turnLabelLabel.text = "エネミ`\nタ`ン";
        turnLabelLabel.style.color = new StyleColor(Color.red);
    }


    public void OnPlayerTurnBegin()
    {
        endTurnButton.SetEnabled(true);     //プレイヤ`タ`ン中はボタンが有郡摔胜

        turnLabelLabel.text = "プレイヤ`\nタ`ン";
        turnLabelLabel.style.color = new StyleColor(Color.white);
    }
}
